spring:
  application:
    name: 03-Config-Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/padhibailochan19/ecom_confugration_properties
          clone-on-start: true
    
server:
  port: 4444
  
  
